name: my-broadband
recipe: laravel
config:
  webroot: public
  php: '8.0'
  via: nginx
  cache: redis
  composer_version: 2-latest

services:
  node:
    type: node:14
  mailhog:
    type: mailhog:v1.0.0
    portforward: true
    hogfrom:
      - appserver
  appserver:
    type: php:8.0
    xdebug: true
    build:
      - php artisan storage:link

tooling:
  npm:
    service: node
  setup:
    service: appserver
    cmd:
      - composer install
      - php artisan key:generate
      - php artisan migrate --seed
      - php artisan storage:link

  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
    user: root

  xdebug-off:
    service: appserver
    description: Disable xdebug for nginx.
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
    user: root