name: my-broadband
recipe: laravel
config:
  webroot: public
  php: '8.0'
  via: nginx
  cache: redis
  composer_version: 2-latest

services:
  node:
    type: node:14
  mailhog:
    type: mailhog:v1.0.0
    portforward: true
    hogfrom:
      - appserver
  appserver:
    type: php
    build:
      - php artisan storage:link

tooling:
  npm:
    service: node
  setup:
    - composer install
    - php artisan key:generate
    - php artisan storage:link
